config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    get 'profile/:id', to: 'profiles#show', as: :user_root # Keep as user_root
    get 'profile/edit/:id', to: 'profiles#edit', as: :edit_profile
    patch 'profile', to: 'profiles#update'
  end

  resources :wallets do
    member do
      post :add_shards
      post :subtract_shards
      get :buy_shards
      post :purchase_shards
    end
  end

  resources :items do
    member do
      post :purchase
    end
  end

  resources :servers do
    member do
      post :start_game
      post :join_game
      post :generate_background
    end
    resources :server_users, only: [:create, :destroy] do
      collection do
        delete :leave
      end
    end
    resources :games do
      member do
        post'perform_action'
        get :current_turn
        get :update_game_board
        get :update_current_turn
        get :update_inventory
        get :update_treasures
        get :update_opponent_details
        get :update_player_stats
        get :update_game_area
        get :update_game_right_panel
        get :update_game_over
        get :update_show
        get :update_game_left_panel
      end
    end
  end

  resources :grid_cells
  resources :transactions
  resources :inventories
  resources :contents
  resources :treasures
  resources :treasure_finds
  resources :scores
  resources :leaderboards
  resources :leaderboard_entries

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/profiles_controller.rb
# app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  # GET /profile/edit
  def edit
    @user = current_user
  end

  # GET /profile
  def show
    @user = current_user
  end

  # PUT /profile
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_root_path, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :role)
  end
end

app/views/profiles/edit.html.haml
- provide(:title, "Edit Profile")
= action_cable_meta_tag
= content_tag(:meta, nil, name: "cable-token", content: "#{current_user&.cable_token}")

%h1 Edit Profile

= form_with(model: @user, url: profile_path, method: :patch) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :username
    = f.text_field :username, class: "form-control", title:"This field is how others will see your name."

  .form-group
    = f.label :email
    = f.email_field :email, class: "form-control", title:"This field is how you login and where system mail will go."

  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control", autocomplete: "off", title:"Standard password stuff. It needs to be >8 chars in length."

  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control", autocomplete: "off", title:"Retype in your password to make sure there is no typos."

  .form-group
    = f.label :role
    = f.select :role, options_for_select([['Player', 'player'], ['Admin', 'admin']], selected: @user.role), class: "form-control", title:"The only difference is that one can add items..."

  .form-group
    = f.submit "Save Changes", class: "btn btn-primary", title:"This will write to your account. Are you sure you want to do this?"

%p
  = link_to 'Back to Profile', user_root_path(current_user.id), class: "btn btn-secondary", title:"Don't save, return back to stats. This is identical to the header button."

app/views/profiles/show.html.haml
- provide(:title, "Profile")
= action_cable_meta_tag
= content_tag(:meta, nil, name: "cable-token", content: "#{current_user&.cable_token}")

%section.profile-container.d-flex.justify-content-between.align-items-start
  %div.profile-left.w-50
    %div.profile-header
      %h1.display-4.text-color-secondary.text-shadow Profile

    %div.profile-info.mt-4.text-color-secondary
      %p
        %strong Username:
        = @user.username
      %p
        %strong Email:
        = @user.email

      %div.profile-actions.mt-3
        = link_to 'Edit Profile', edit_profile_path, class: "btn btn-primary my-2", title: 'Want to change your username, email, or password?'
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-secondary", title: 'Please don\'t go! There\'s still fun awaiting for you!'

  %div.actions-right.w-50.text-center
    %div.actions-header
      %h2.display-5.text-color-secondary.text-shadow Actions

    %div.actions-list-container.mt-4
      %ul.actions-list
        %li= link_to 'Create Server', new_server_path, title: 'This creates a game that you can play on.'
        %li= link_to 'Your Servers', servers_path, title: 'This takes you to the list of games that you have created.'
        %li= link_to 'Items', items_path, title: 'This takes you to the items shop, where you can buy custom objects to boost your ability in the game.'
        %li= link_to 'View Inventory', inventories_path, title: 'This takes you to your inventory, where you can see all the things you\'ve purchased.'
        %li= link_to 'View Transactions', transactions_path, title: 'This takes you to all the purchases you have done (with money).'
        %li= link_to 'My Wallet', wallets_path, title: 'This takes you to your money (shards) management, where you can see how much you have/buy more.'