config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    get 'profile/:id', to: 'profiles#show', as: :user_root # Keep as user_root
    get 'profile/edit/:id', to: 'profiles#edit', as: :edit_profile
    patch 'profile', to: 'profiles#update'
  end

  resources :wallets do
    member do
      post :add_shards
      post :subtract_shards
      get :buy_shards
      post :purchase_shards
    end
  end

  resources :items do
    member do
      post :purchase
    end
  end

  resources :servers do
    member do
      post :start_game
      post :join_game
      post :generate_background
    end
    resources :server_users, only: [:create, :destroy] do
      collection do
        delete :leave
      end
    end
    resources :games do
      member do
        post'perform_action'
        get :current_turn
        get :update_game_board
        get :update_current_turn
        get :update_inventory
        get :update_treasures
        get :update_opponent_details
        get :update_player_stats
        get :update_game_area
        get :update_game_right_panel
        get :update_game_over
        get :update_show
        get :update_game_left_panel
      end
    end
  end

  resources :grid_cells
  resources :transactions
  resources :inventories
  resources :contents
  resources :treasures
  resources :treasure_finds
  resources :scores
  resources :leaderboards
  resources :leaderboard_entries

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user

  validates :balance, numericality: { greater_than_or_equal_to: 0 }, presence: true

  def add(amount)
    update!(balance: balance + amount)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wallet, only: %i[show edit update destroy add_shards subtract_shards buy_shards purchase_shards]

  # GET /wallets
  def index
    @wallet = current_user.wallet
  end

  # GET /wallets/:id
  def show
  end
  # GET /wallets/:id/buy_shards
  def buy_shards
    # Displays the shard purchase form
  end

  def purchase_shards
    amount = params[:amount].to_i

    if amount.positive?
      # Simulate payment processing
      sleep(3) # Fake delay of 3 seconds to simulate processing
      @wallet.balance += amount

      # w/o space length == 16 and all of it is numbers
      cleaned_number = params[:credit_card_number].gsub(/\s+/, "")
      if cleaned_number.length != 16 || !cleaned_number.match?(/\A\d+\z/)
        redirect_to buy_shards_wallet_path(@wallet), alert: "Invalid card info: Card number must be 16 digits long."

      elsif params[:cvv].length != 3 || !params[:cvv].match?(/\A\d+\z/)
        redirect_to buy_shards_wallet_path(@wallet), alert: "Invalid card info: CVV must be 3 digits long."

      elsif !params[:expiry_date].match?(/^(0[1-9]|1[0-2])\/(0[0-9]|1[0-9]|2[0-9])$/)
        redirect_to buy_shards_wallet_path(@wallet), alert: "Invalid card info: Expiry date is in wrong format"
  
      else
        trans = current_user.transactions.build()
        trans.amount = amount
        trans.description = "Shards"
        trans.quantity = amount
        trans.transaction_type = "purchase"
        trans.currency = params[:currency]
        trans.payment_method = "Credit Card: " + params[:credit_card_number][-4..-1]

        trans.save!()

        if @wallet.save     
          redirect_to @wallet, notice: "#{amount} Shards successfully purchased!"
        else
          # :nocov:
          redirect_to buy_shards_wallet_path(@wallet), alert: "Failed to update wallet."
          # :nocov:
        end
      end
    else
      redirect_to buy_shards_wallet_path(@wallet), alert: "Invalid amount. Please enter a positive number."
    end
  end
  # GET /wallets/new
  def new
    @wallet = current_user.build_wallet
  end

  # POST /wallets
  def create
    @wallet = current_user.build_wallet(wallet_params)
    if @wallet.save
      redirect_to @wallet, notice: 'Wallet was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /wallets/:id/edit
  def edit
  end

  # PATCH/PUT /wallets/:id
  def update
    if @wallet.update(wallet_params)
      redirect_to @wallet, notice: 'Wallet was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /wallets/:id
  def destroy
    @wallet.destroy
    redirect_to wallets_url, notice: 'Wallet was successfully destroyed.'
  end

  # POST /wallets/:id/add_shards
  def add_shards
    shard_amount = params[:amount].to_i
    if shard_amount.positive?
      @wallet.balance += shard_amount
      if @wallet.save
        redirect_to @wallet, notice: "#{shard_amount} Shards successfully added"
      else
        # :nocov:
        redirect_to @wallet, alert: "Operation Failed"
        # :nocov:
      end
    else
      redirect_to @wallet, alert: "Invalid amount"
    end
  end

  # POST /wallets/:id/subtract_shards
  def subtract_shards
    amount = params[:amount].to_i
    if amount.positive? && @wallet.balance >= amount
      @wallet.balance -= amount
      if @wallet.save
        redirect_to @wallet, notice: "#{amount} Shards removed from account"
      else
        # :nocov:
        redirect_to @wallet, alert: "Operation Failed" 
        # :nocov:
      end
    else
      redirect_to @wallet, alert: "Insufficient Funds or Invalid Amount"
    end
  end

  private

  def set_wallet
    @wallet = current_user.wallet
  end

  def wallet_params
    params.require(:wallet).permit(:balance)
  end
end

app/views/wallets/buy_shards.html.haml
%head
  = javascript_include_tag "channels/purchase_shards.js"

%div.row.d-flex.justify-content-center
  %div.col-md-8
    %div.card.text-color-secondary.bg-dark.bg-opacity-75.my-3
      %div.card-body
        %h4.card-title.text-center Buy Shards
        <hr />
        %p
          %h6.text-center.font-monospace.my-2 1 Shard = $0.01 USD.
          %h6 Enter the number of shards you want to purchase and your payment details:

        = form_with url: purchase_shards_wallet_path(@wallet), method: :post, local: true, id: "shard-purchase-form" do |f|
          .form-group
            = f.label :amount, "Number of Shards:"
            = f.number_field :amount, min: 1, class: 'form-control', id: "shard-amount"

          %h5 Payment Details:
          <hr />
          .form-group
            = f.label :credit_card_number, "Credit Card Number:"
            = f.text_field :credit_card_number, placeholder: "1234 5678 9012 3456", class: 'form-control'
          .form-group
            = f.label :expiry_date, "Expiry Date (MM/YY):"
            = f.text_field :expiry_date, placeholder: "MM/YY", class: 'form-control'
          .form-group
            = f.label :cvv, "CVV:"
            = f.text_field :cvv, placeholder: "123", maxlength: 3, class: 'form-control'
          .form-group
            = f.label :currency, "Currency:"
            = f.select :currency, options_for_select([['USD', 'USD'], ['JPY', 'JPY'], ['EUR', 'EUR']], 'USD'), class: 'form-control', id: "curr-select"

          .actions
            = f.submit 'Purchase Shards - $0.00', class: 'btn btn-success text-color-secondary w-100', id: "purchase-button"

        .actions.mt-2
          = link_to 'Back to Wallet', wallet_path(@wallet), class: 'btn btn-secondary w-100'

app/views/wallets/edit.html.haml
%div.row.d-flex.justify-content-center
  %div.col-md-6
    %div.card.text-color-secondary.bg-dark.bg-opacity-75
      %div.card-body
        %h4.card-title.text-center Edit Wallet
        = form_with model: @wallet, local: true do |f|
          .form-group
            = f.label :balance, "Current Balance:"
            = f.number_field :balance, class: 'form-control'

          %div
            .actions
              = f.submit 'Update Wallet', class: 'btn btn-primary w-100'

            .actions.mt-2
              = link_to 'Back to Wallets', wallets_path, class: 'btn btn-secondary w-100'


app/views/wallets/index.html.haml
%div.row.d-flex.justify-content-center
  %div.col-md-6
    %div.card.text-color-secondary.bg-dark.bg-opacity-75
      %div.card-body
        %h4.card-title.text-center Your Wallet
        - if @wallet.present?
          %p
            %h5 
            Balance: 
            = @wallet.balance 
            Shards

          %p
            %h5 
            Wallet Created At:
            = @wallet.created_at.strftime('%B %d, %Y %H:%M:%S')

          %div.d-flex.justify-content-center
            .actions
            = button_to 'Delete Wallet', wallet_path(@wallet), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-color-secondary me-2'
            = link_to 'Buy Shards', buy_shards_wallet_path(@wallet), class: 'btn btn-success text-color-secondary me-2'
            = link_to 'Back to Servers', servers_path, class: 'btn btn-dark text-color-secondary'

        - else
          %p.text-color-secondary You do not have a wallet yet.
          %div.d-flex.justify-content-center
            = link_to 'Create Wallet', new_wallet_path, class: 'btn btn-success text-color-secondary me-2'
            = link_to 'Back to Servers', servers_path, class: 'btn btn-secondary'




app/views/wallets/new.html.haml
%div.row.d-flex.justify-content-center
  %div.col-md-6
    %div.card.text-color-secondary.bg-dark.bg-opacity-75
      %div.card-body
        %h4.card-title.text-center Create New Wallet
        = form_with model: @wallet, local: true do |f|
          .form-group
            = f.label :balance, "Initial Balance:"
            = f.number_field :balance, value: 500, min: 0, class: 'form-control'

          %div
            .actions
              = f.submit 'Create Wallet', class: 'btn btn-success text-color-secondary w-100 mb-2'

          .actions
            = link_to 'Back to Wallets', wallets_path, class: 'btn btn-primary w-100'

app/views/wallets/show.html.haml
%div.row.d-flex.justify-content-center
  %div.col-md-6
    %div.card.text-color-secondary.bg-dark.bg-opacity-75
      %div.card-body
        %h4.card-title.text-center Wallet Details
        - if @wallet.present?
          %p
            %strong Balance:
            = @wallet.balance
            %span Shards
          %p
            %strong Wallet Created At:
            = @wallet.created_at.strftime('%B %d, %Y %H:%M:%S')

          %div.d-flex.justify-content-center    
            .actions
              = link_to 'Edit Wallet', edit_wallet_path(@wallet), class: 'btn btn-primary me-2'
              = link_to 'Back to Wallets', wallets_path, class: 'btn btn-secondary'

        - else
          %h6.text-secondary No wallet found.
          .actions
            = link_to 'Back to Wallets', wallets_path, class: 'btn btn-secondary'
